name: service container demo

on:                                  
  workflow_dispathc
  push:
  
 jobs:
   ant01:
   runs-on: ubuntu-latest
   steps:
   -asdf
   services:
   mydatabase:
    image: mysql: 8.0.33
    ports:
    - 3306:3306
    emv:
     MYSQL_ROOT_PASSWORD: Akash@52
